In [1]:
import numpy as np
import sys

# Tamanho dos itens

In [2]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])

In [3]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
sys.getsizeof(a)

104

In [5]:
b.nbytes

20

# Numero de dimensões

In [6]:
#array 1D
d1 = np.array([1,2,3])
print(d1)
print(d1.shape)
print("numero de dimensoes:",d1.ndim)

[1 2 3]
(3,)
numero de dimensoes: 1


In [7]:
d2 = np.array([[1,2,3],[4,5,6]])
print(d2)
print(d2.shape)
print("numero de dimensoes:",d2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
numero de dimensoes: 2


In [11]:
d3 = np.array([[[1,2,3],[4,5,6],[8,9,0],[11,12,13]],[[1,2,3],[4,5,6],[8,9,0],[11,12,13]]])
print(d3)
print(d3.shape)
print("numero de dimensoes:",d3.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9  0]
  [11 12 13]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 8  9  0]
  [11 12 13]]]
(2, 4, 3)
numero de dimensoes: 3


# Somando listas

In [9]:
a = [2,3,4]
b = [2,3,4]
result = a + b
print(result)

[2, 3, 4, 2, 3, 4]


In [10]:
a = np.array([2,3,4])
b = np.array([2,3,4])
result = np.add(a,b)
print(result)

[4 6 8]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
# array[row,col]
result = np.array(a[1,1] + a[0,1])
print(result)


7
